name: deploy to gae

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4     
      - name: Install Python
        uses: actions/setup-python@v5  
        with:
            python-version: '3.11' 
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "1.1.7"
              
      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SA_CREDS }}  
             
      - name: Terraform Format
        run: terraform fmt
        env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SA_CREDS }}  
    
      - name: Terraform Plan
        run: terraform plan -input=false
        env:
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SA_CREDS }}  
    
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SA_CREDS }}
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json:  ${{ secrets.GOOGLE_SA_CREDS }}
            
      - name: Set Google OAuth Access Token
        run: echo "GOOGLE_OAUTH_ACCESS_TOKEN=${{ steps.auth.outputs.access_token }}" >> $GITHUB_ENV               
                       
      - name: Login to Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev          
             
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
            context: .
            push: true
            tags: us-central1-docker.pkg.dev/gcpa-415907/app-engine/amazon_seller_ai:latest

      - name: Deploy to GAE
        run: |
          gcloud app deploy --image-url=us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/app-engine/amazon_seller_ai:latest
          # Check the exit code of the deployment command
          if [[ $? -ne 0 ]]; then
            echo "Deployment failed! Check the workflow logs for details."
            exit 1
          fi          

    
